# Generated by Django 2.0.5 on 2019-05-06 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id_file', models.BigAutoField(primary_key=True, serialize=False)),
                ('path_file', models.FilePathField(default=None)),
                ('log_path_file', models.FilePathField(default=None)),
                ('status', models.CharField(default='stand-by', max_length=100)),
                ('is_opt', models.BooleanField(default=False)),
                ('is_opt_es_et', models.BooleanField(default=False)),
                ('is_freq', models.BooleanField(default=False)),
                ('is_freq_es_et', models.BooleanField(default=False)),
                ('is_sp', models.BooleanField(default=False)),
                ('is_td', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'imported file',
            },
        ),
        migrations.CreateModel(
            name='ImportRule',
            fields=[
                ('id_rule', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule', models.CharField(default='manual', max_length=40)),
            ],
            options={
                'verbose_name': 'rule of import',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id_job_type', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_software', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id_version', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_number', models.CharField(default=None, max_length=40)),
                ('id_software', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='import_qcpia.Software')),
            ],
            options={
                'verbose_name': 'software version',
            },
        ),
        migrations.AddField(
            model_name='importrule',
            name='id_job_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='import_qcpia.JobType'),
        ),
        migrations.AddField(
            model_name='importrule',
            name='id_software',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='import_qcpia.Software'),
        ),
        migrations.AddField(
            model_name='importrule',
            name='id_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='import_qcpia.SoftwareVersion'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='id_job_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='import_qcpia.JobType'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='id_software',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='import_qcpia.Software'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='id_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importfile',
            name='id_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='import_qcpia.SoftwareVersion'),
        ),
    ]
