# Generated by Django 2.0 on 2018-04-23 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cid', models.BigIntegerField(default=None, null=True)),
                ('iupac', models.TextField(default=None, null=True)),
                ('inchi', models.TextField(default=None, null=True)),
                ('smiles', models.TextField(default=None, null=True)),
                ('formula', models.TextField(default=None, null=True)),
                ('method', models.TextField(default=None, null=True)),
                ('nuclear_starting_energy', models.BigIntegerField(default=None, null=True)),
                ('nuclear_ending_energy', models.BigIntegerField(default=None, null=True)),
                ('charge', models.IntegerField(default=None, null=True)),
                ('theory', models.CharField(default=None, max_length=10, null=True)),
                ('software', models.CharField(default=None, max_length=20, null=True)),
                ('functional', models.CharField(default=None, max_length=20, null=True)),
                ('path', models.FilePathField(allow_folders=True, null=True)),
                ('cansmiles', models.CharField(default=None, max_length=100)),
                ('multiplicity', models.IntegerField(default=None, null=True)),
                ('basis_set_name', models.CharField(default=None, max_length=100, null=True)),
                ('basis_set_size', models.IntegerField(default=None, null=True)),
                ('solvent_method', models.CharField(default=None, max_length=100, null=True)),
                ('solvent', models.CharField(default=None, max_length=100, null=True)),
                ('starting_energy', models.IntegerField(default=None, null=True)),
                ('ending_energy', models.IntegerField(default=None, null=True)),
                ('homo', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=None), default=None, null=True, size=None)),
            ],
            options={
                'verbose_name': 'query',
            },
        ),
    ]
