# Generated by Django 2.0 on 2018-04-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='functionnal',
            fields=[
                ('id_functionnal', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=15)),
            ],
            options={
                'verbose_name': 'functionnal',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id_job_type', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'job_type',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('files_path', models.FilePathField(allow_folders=True, default=None)),
                ('cid', models.BigIntegerField(default=None, null=True)),
                ('iupac', models.CharField(default=None, max_length=500, null=True)),
                ('inchi', models.CharField(default=None, max_length=1000)),
                ('smiles', models.CharField(default=None, max_length=500)),
                ('cansmiles', models.CharField(default=None, max_length=500)),
                ('formula', models.CharField(default=None, max_length=30, null=True)),
                ('charge', models.SmallIntegerField(default=0)),
                ('multiplicity', models.SmallIntegerField(default=None)),
                ('basis_set_name', models.CharField(default=None, max_length=20, null=True)),
                ('basis_set_size', models.IntegerField(default=None)),
                ('solvatation_method', models.CharField(default=None, max_length=10, null=True)),
                ('solvent', models.CharField(default='GAS', max_length=40)),
                ('starting_nuclear_repulsion_energy', models.FloatField(default=None)),
                ('ending_nuclear_repulsion_energy', models.FloatField(default=None)),
                ('starting_energy', models.FloatField(default=None, null=True)),
                ('ending_energy', models.FloatField(default=None)),
                ('homo_alpha_energy', models.FloatField(default=None, null=True)),
                ('homo_beta_energy', models.FloatField(default=None, null=True)),
                ('lumo_alpha_energy', models.FloatField(default=None, null=True)),
                ('lumo_beta_energy', models.FloatField(default=None, null=True)),
                ('functional', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.functionnal')),
                ('job_type', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.JobType')),
            ],
            options={
                'verbose_name': 'query',
            },
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id_software', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'software',
            },
        ),
        migrations.CreateModel(
            name='theory',
            fields=[
                ('id_theory', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=10)),
            ],
            options={
                'verbose_name': 'theory',
            },
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('affiliation', models.TextField(default=None)),
                ('orcid', models.CharField(default=None, max_length=19, null=True)),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.AddField(
            model_name='query',
            name='software',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.software'),
        ),
        migrations.AddField(
            model_name='query',
            name='theory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.theory'),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuChemPedIA.utilisateur'),
        ),
    ]
