# Generated by Django 2.0 on 2018-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Path',
            field=models.FilePathField(path='/home/etudiant/Documents/stage/data_brice', recursive=True),
        ),
    ]
