# Generated by Django 2.0.5 on 2018-05-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='functional',
        ),
        migrations.RemoveField(
            model_name='query',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='query',
            name='software',
        ),
        migrations.RemoveField(
            model_name='query',
            name='theory',
        ),
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.DeleteModel(
            name='functionnal',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='software',
        ),
        migrations.DeleteModel(
            name='theory',
        ),
    ]
