# Generated by Django 2.0.5 on 2018-07-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='id_job_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuChemPedIA.JobType'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='id_software',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuChemPedIA.Software'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='id_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuChemPedIA.SoftwareVersion'),
        ),
    ]
