# Generated by Django 2.0.5 on 2018-06-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='name',
        ),
    ]
