# Generated by Django 2.0.5 on 2018-06-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='status',
            field=models.CharField(default='Stand-by', max_length=100),
        ),
    ]
