# Generated by Django 2.0.5 on 2018-06-12 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id_file', models.BigAutoField(primary_key=True, serialize=False)),
                ('path_file', models.FilePathField(default=None)),
                ('status', models.CharField(default='Stand by', max_length=100)),
                ('id_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
