# Generated by Django 2.0.5 on 2018-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='affiliation',
            field=models.TextField(default=None, null=True),
        ),
    ]
