# Generated by Django 2.0.5 on 2018-06-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0002_auto_20180629_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRule',
            fields=[
                ('id_rule', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule', models.CharField(default='Manual', max_length=40)),
            ],
            options={
                'verbose_name': 'rule of import',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_software', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id_version', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_number', models.CharField(default=None, max_length=40)),
                ('id_software', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.Software')),
            ],
            options={
                'verbose_name': 'software version',
            },
        ),
        migrations.AddField(
            model_name='importrule',
            name='id_software',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.Software'),
        ),
        migrations.AddField(
            model_name='importrule',
            name='id_version',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.SoftwareVersion'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='id_software',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuChemPedIA.Software'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='id_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuChemPedIA.SoftwareVersion'),
        ),
    ]
