# Generated by Django 2.0.5 on 2018-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0002_auto_20180711_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='status',
            field=models.CharField(default='stand-by', max_length=100),
        ),
    ]
