# Generated by Django 2.0.5 on 2018-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0002_auto_20180610_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
