# Generated by Django 2.0.5 on 2018-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0003_auto_20180711_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='city',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='country',
            field=models.TextField(default=None, null=True),
        ),
    ]
