# Generated by Django 2.0.5 on 2018-07-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0003_auto_20180629_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrule',
            name='rule',
            field=models.CharField(default='manual', max_length=40),
        ),
    ]
