# Generated by Django 2.0.5 on 2018-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0003_auto_20180610_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
