# Generated by Django 2.0.5 on 2018-07-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuChemPedIA', '0004_auto_20180713_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrule',
            name='id_software',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.Software'),
        ),
        migrations.AlterField(
            model_name='importrule',
            name='id_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='QuChemPedIA.SoftwareVersion'),
        ),
    ]
